[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://events.rsglab.online/*"
  to = "/events/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://events.rsglab.online"
  to = "/events"
  status = 200
  force = true 