[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://events.rsglab.online"
  to = "https://rsglab.online/events"
  status = 301
  force = true

[[redirects]]
  from = "https://events.rsglab.online/*"
  to = "https://rsglab.online/events/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 