[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://events.rsglab.online"
  to = "/events/index.html"
  status = 200

[[redirects]]
  from = "https://events.rsglab.online/*"
  to = "/events/:splat/index.html"
  status = 200

[[redirects]]
  from = "https://events.rsglab.online/*/"
  to = "/events/:splat/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin" 